// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdNIOldTDj_rRu3SKjoNNdtbaKwnGB6Tw',
    appId: '1:1007341160595:web:609321dfa95e06a488e566',
    messagingSenderId: '1007341160595',
    projectId: 'foo-app-473809',
    authDomain: 'foo-app-473809.firebaseapp.com',
    storageBucket: 'foo-app-473809.firebasestorage.app',
    measurementId: 'G-CZ9ZRFQME6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_DHzLG4v6_NphvXULa_FQy0CPlEMODo',
    appId: '1:1007341160595:android:0bce83f1e0274e6788e566',
    messagingSenderId: '1007341160595',
    projectId: 'foo-app-473809',
    storageBucket: 'foo-app-473809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5Shdms17sb0GdgeheysbBMFzX5SVMQ4',
    appId: '1:1007341160595:ios:156809067b175b1988e566',
    messagingSenderId: '1007341160595',
    projectId: 'foo-app-473809',
    storageBucket: 'foo-app-473809.firebasestorage.app',
    androidClientId: '1007341160595-mil3f96n5c05rtghopleiv3ej6a5dh42.apps.googleusercontent.com',
    iosClientId: '1007341160595-fp042unijclp7kngur377ro494sb9f7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mumiappfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5Shdms17sb0GdgeheysbBMFzX5SVMQ4',
    appId: '1:1007341160595:ios:156809067b175b1988e566',
    messagingSenderId: '1007341160595',
    projectId: 'foo-app-473809',
    storageBucket: 'foo-app-473809.firebasestorage.app',
    androidClientId: '1007341160595-mil3f96n5c05rtghopleiv3ej6a5dh42.apps.googleusercontent.com',
    iosClientId: '1007341160595-fp042unijclp7kngur377ro494sb9f7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mumiappfood',
  );
}
